
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณFUNF3COM  บAutor  ณSangelles          บ Data ณ  12/18/16   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/


user function FUNF3COM

Local cUpdate := ""
Local nStart  := 0

    cUpdate := " UPDATE " + RetSqlName("SX3")
    cUpdate += " SET X3_F3 = 'SF4' WHERE X3_CAMPO = 'D1_TES' "
    If TCSQLExec(cUpdate) < 0
    		FwLogMsg("FUNF3COM", /*cTransactionId*/, "FUNF3COM", FunName(), "", "01", "Erro ao Executar o update tabela SX3.", 0, (nStart - Seconds()), {})
    EndIf 
                       
    MATA116()

    cUpdate := " UPDATE " + RetSqlName("SX3")
    cUpdate += " SET X3_F3 = 'SFMCU' WHERE X3_CAMPO = 'D1_TES' "
    If TCSQLExec(cUpdate) < 0
    		FwLogMsg("FUNF3COM", /*cTransactionId*/, "FUNF3COM", FunName(), "", "01", "Erro ao Executar o update tabela SX3.", 0, (nStart - Seconds()), {})
    EndIf 

return
